var GAME_LEVELS = [
  ["                                                                               ",
  "                                                                                ",
  "                                                                                ",
  "                                    xxxxxxxx                                    ",
  "                                   v !!!!!! v                                   ",
  "                                                                                ",
  "                                                                                ",
  "                                       oo                oo                     ",
  "   s                                  xxxx              xxxx                    ",
  "  xxx                                  tt                                       ",
  "  x                                                    x!!!!x                   ",
  "  x          xxxxxxxxx                                xx!!!!xx             xx   ",
  "  x         xxxxxxxxxx=                               =xxxxxx                x  ",
  "  x        xxxxxxxxxxx             xxxx!!!!xxxx  oo                          x  ",
  "  x       xxxxxxxxxxxx!!!!xxxxx      xx!!!!xx    xx     xxx                  x  ",
  "  x      xxxxxxxxxxxxx!!!!xxxxx                                   ooo        x  ",
  "  x  @  xxxxxxxxxxxxxx!!!!xxxxx          e                       xxxxx       x  ",
  "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!xxxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
  "                              x!!xx                  x     x                    ",
  "                              x!!xx                  x!!!!!x                    ",
  "                              x!!xx                  x!!!!!x                    ",
  "                              xxxxx                  xxxxxxx                    ",
  "                                                                                ",
  "                                                                                "],
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                       x=   oo   =x                                             ",
   "                       !xxxxxxxxxx!                                             ",
   "                      xv     e    vx                                            ",
   "                     x              x                                           ",
   "      xxxxxx!xxxxxxx!       oo       !xxxxxxx!                                  ",
   "      v     !=  t  =!       xx        x  t  x                                  ",
   "  o                                    v                                        ",
   "  xxxx                     xttx                                                 ",
   "  x                                                                             ",
   "  x                                                xxxxx!!xxxxxx                ",
   "  x                  x!     ==      x             x    x!!x     x              x",
   "  x=      x|x                                    x     x!!x      x             x",
   "  x      x!!x   xxx       xxxx        xxx       x      x!!x       x   o        x",
   "  x     xx!!x                                  x        xx         x           x",
   "  x@   xxx!!x                                 x                     x          x",
   "  xxxxxxxxxxxxx!!!!xxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "             xx!!!!x                  x!!!!!x                                   ",
   "             xx!!!!x                  x!!!!!x                                   ",
   "             xx!!!!x                  x!!!!!x                                   ",
   "              xxxxx                    xxxxx                                    ",
   "                                                                                ",
   "                                                                                "],
   ["                                                                               ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                       xxxxxxxxx                                ",
   "                                       v   e   v                                ",
   "   s             oo                                                             ",
   "  xxx                                                                           ",
   "  x                                                                             ",
   "  x          xxx!!!!xxx                                                         ",
   "  x         xxxx!!!!xxxx                               ooo                   x  ",
   "  x        xxxxx!!!!xxxxx                                             x      x  ",
   "  x       xxxxxx!!!!xxxxxx                 o                          xx     x  ",
   "  x      xxxxxxx!!!!xxxxxxx=          =xxxxxxxxx                    xxx      x  ",
   "  x  @  xxxxxxxx!!!!xxxxxxxx        o  xxxxxxxxx                   xxxx    o x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxx  ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "]

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
